# Stage 1: Builder
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install --force
RUN rm -rf node_modules
COPY . .
RUN npm install --force
RUN npm run build

# Stage 2: Runner (simplificado)
FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app ./

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV APP_KEY=GTs_pMakZaAEC4kL7695m8KMyMADaKaf
ENV DB_HOST=mysql
ENV DB_USER=admin
ENV DB_PASSWORD=admin
ENV DB_DATABASE=main 
ENV MS_SECURITY=http://ms-security:8080
ENV DB_PORT=3306
ENV DB_CONNECTION=mysql

CMD ["node", "build/server.js"]