# Utiliza una imagen base oficial de Python
FROM python:3.9-slim-buster AS builder

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo de requisitos
COPY requirements.txt .

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copia el código fuente de la aplicación
COPY . .

# Expone el puerto en el que la aplicación de notificaciones escucha (ejemplo: 8081)
EXPOSE 8081

# Define el comando para ejecutar la aplicación (ejecuta server.py directamente)
CMD ["python", "server.py"]